### PR TITLE
Features/mips64

### PR DESCRIPTION
**Pull request by jonwilson030981**
Support for MIPS64

Grateful for any comments/suggestions/improvements.

Note this adds support for gum only, GumJS is dependent on libffi to allow javascript JIT code to be executed, but this doesn't appear to support MIPS64 very well. This would be useful in future, but this change at least allows users to write and integrate their hooks written in C.

### CODE REVIEW

**Comment by oleavr** [comment]
Sweet! Only two minor issues we need to sort out:
- `FRIDA_LIBC` has a slightly odd-looking default, even if it makes sense on these embedded targets. (Though it's only confusing because the variable is only used for said targets.)
- Need to resolve the conflicts and mask out the submodule changes.

**Comment by jonwilson030981** [comment]
I set FRIDA_LIBC based on the cross-compilers which were packaged as part of Ubuntu 18.04, but as this can be overridden by the command-line, I am happy for it to be changed to whichever default makes most sense.

I'm not quite sure how to fix the submodule issues. Is this something that needs to wait until the changes for frida-gum are merged?

**Comment by oleavr** [comment]
Ah I see, makes sense. I was just wondering if maybe we should make the default value be `glibc`, as this is what we assume on the other architectures. I'll go ahead and merge shortly.

**Comment by oleavr** [comment]
Merged with minor tweaks as a448b5dd283f79afdd75a299c4ae32ded7948931.

Thanks for the awesome contributions! :heart:

**Pull request closed without merging**
