### PR TITLE
Upgrade NDK version to r20

### PR DESCRIPTION
**Pull request by muhzii**
Upgrade the version of the required NDK to r20.
Also add build target for Python bindings on Android and add PYTHON_INCDIR option for meson build configuration.

### CODE REVIEW

**Comment by oleavr** [comment]
Upgrading the NDK means GCC is gone and `Makefile.sdk.mk` no longer builds due to one of the dependencies using a GCC-only feature. Happy to merge this once that's resolved (by patching that dependency if upstream didn't already fix it).

**Comment by muhzii** [comment]
@oleavr Thanks for your response. 
Oops, apparently, I didn't watch out for the SDK build. so I took a  at that dependency (elfutils) and due to using

**Comment by muhzii** [comment]
Hello @oleavr ,
I have patched the dependency (elfutils) to compile with clang.. most of the patches to the library is for moving nested functions out or defining them as macros. Other changes for dual support (gcc & clang) of switch statement fall-through warning-suppression.

**Comment by oleavr** [comment]
Thanks @muhzii! Did you try building and running Frida from the resulting SDK?

**Comment by muhzii** [comment]
@oleavr yes, tested for android-x86. This PR is for adapting the v8 build to the newer NDK https://github.com/frida/v8-build/pull/1

**Pull request merged**
