### PR TITLE
Add a tarball to the windows devkits

### PR DESCRIPTION
**Pull request by s1341**
This should make everyone's life easier, especially as we try to implement this issue: https://github.com/meme/frida-rust/issues/9

### CODE REVIEW

**Comment by oleavr** [comment]
Thanks!

**Comment by oleavr** [comment]
This broke the release script. Note to self: We need to enhance the CI so it does a dry-run release on every build, and make it run for PRs too.

**Comment by s1341** [comment]
Sorry about that....

**Comment by oleavr** [comment]
No worries. It's as much my fault for botching the review 😅

**Pull request merged**
