### PR TITLE
Make the default of the PYTHON variable consistent

### PR DESCRIPTION
**Pull request by Tyilo**
in the mac and linux makefile.

### CODE REVIEW

**Comment by oleavr** [comment]
I don't think the `-f` option exists in the BSD readlink; did you check if this works on Mac?

**Comment by Tyilo** [comment]
You're right. Is there even a reason that we need to resolve the symlink if `PYTHON` is a symlink?

**Comment by oleavr** [comment]
Ok. It's just to have the directories not clash inside build, so you can do "make" and later "make PYTHON=/foo" to build another python binding side-by-side.

**Comment by Tyilo** [comment]
That explains why we need to get the path to the python binary, but not why we need to resolve the symlink.

**Comment by oleavr** [comment]
Because `which python` might be a symlink, and we use its basename to name the directory. Ideally we want it to end up as e.g. lib/python2.7, so you can do `make PYTHON=/usr/local/bin/python3.4` later to have lib/python3.4 side-by-side.

**Comment by Tyilo** [comment]
Say I have two versions of python 2.7.x installed, eg. OS X system one and another one from homebrew, would they be built side by side?
If yes, then we need to resolve the symlink.
If no, we just need to detect the python version, which we should do by running `$(PYTHON) -c 'import sys; v = sys.version_info; print "{}.{}".format(v[0], v[1])'`

**Comment by oleavr** [comment]
No, they'll still clash. This is however not a very important feature. I'd say just to proper detection like you mentioned, it's way better anyway.

**Comment by oleavr** [comment]
Sweet!

**Pull request merged**
